language: python
python: 3.8

services:
  - postgresql

install:
  - pip install -e . -r requirements.txt

env:
  global:
  - SECRET_KEY="i1bn=oly)w*2yl-5yc&f!vvgt)p)fh3_2$r#spa!*sw36f5ov7"
  - GH_TOKEN="dummygithubtoken"

before_script:
  - psql -c "CREATE DATABASE vulnerablecode;" -U postgres
  - ./manage.py migrate

script:
  - ./manage.py collectstatic
  - python -m pytest -v -m "not webtest"

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b119fa557626081e1f36
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

after_success:
  - coveralls