name: CI
on:
  push:
    branches: [ main ]

  pull_request:
    types: [opened, synchronize]
jobs:
  unit_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.11

      - name: Install dependencies
        run: |
          sudo apt-get install -y postgresql python3-dev libpq-dev build-essential
          make dev envfile

      - name: Validate code format
        run: make check

      - name: Setup database
        run: |
          sudo systemctl start postgresql
          make postgres

      - name: Run tests
        run: make test
        env:
          GH_TOKEN: 1 

      - name: Type Checking
        run: make typecheck
